# Generated by Django 5.0.1 on 2024-03-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_notificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificate',
            name='isRead',
            field=models.BooleanField(default=False, verbose_name='Okundu Bilgisi'),
        ),
    ]
